In [9]:
#拆分成8个bit图层，每个图层是8bit灰度值中的1bit
import cv2
import numpy as np

img = cv2.imread('G:\\MachineLearning\\OpenCV\\1920x1080.JPG',1)
img2gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

print(np.max(img2gray))
cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
cv2.resizeWindow('Source Image', 640, 480)
cv2.imshow('Source Image', img2gray)

allOnes = np.ones_like(img2gray)

bitMash = 1

for i in range(8):
    bitMash = 1 << i
    mashMat = bitMash * allOnes
    #print(mashMat)
    #print(img2gray)
    #print()
    newImg = cv2.bitwise_and(mashMat,img2gray)
    imgName = 'Bit ' + str(i) + " Image"
    cv2.namedWindow(imgName, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(imgName, 640, 480)
    cv2.imshow(imgName, newImg)

cv2.waitKey(0)
cv2.destroyAllWindows()


255


In [1]:
#局部增强
import cv2
import numpy as np


def getNeighbourhood(img, x, y, dim = 3):
    if dim % 2 == 0:
        return
    xAsix = range(x - int(dim / 2), x + int(dim / 2) + 1)
    yAsix = range(y - int(dim / 2), y + int(dim / 2) + 1)
    #print(xAsix)
    #print(yAsix)
    lenOfX = img.shape[1]
    lenOfY = img.shape[0]
    neighbourhoodGray = []
    for i in xAsix:
        for j in yAsix:
            if i >= 0 and i < lenOfX and j >= 0 and j < lenOfY:
                neighbourhoodGray.append(img[j,i])
    return neighbourhoodGray

img = cv2.imread('G:\\MachineLearning\\OpenCV\\1920x1080.JPG',1)
img2gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
cv2.resizeWindow('Source Image', 800, 450)
cv2.imshow('Source Image', img2gray)

[rows,cols] = img2gray.shape
mean_G, stddev_G = cv2.meanStdDev(img2gray)
newImg = img2gray
for x in range(cols):
    for y in range(rows):
        mean, stddev = cv2.meanStdDev(np.array(getNeighbourhood(img2gray,x,y)))
        if mean <= 0.8 * mean_G and stddev >= 0.02 * stddev_G and  stddev <= 0.4 * stddev_G:
            newImg[y,x] = np.min([255, 4 * img2gray[y,x]])

cv2.namedWindow('NewImage', cv2.WINDOW_NORMAL)
cv2.resizeWindow('NewImage', 800, 450)
cv2.imshow('NewImage', newImg)

cv2.waitKey(0)
cv2.destroyAllWindows()




In [12]:
#中值滤波器实现
import cv2
import numpy as np

#注意归一化！！！！！
def getNeighbourhood(img, x, y, dim = 3):
    if dim % 2 == 0:
        return
    xAsix = range(x - int(dim / 2), x + int(dim / 2) + 1)
    yAsix = range(y - int(dim / 2), y + int(dim / 2) + 1)
    #print(xAsix)
    #print(yAsix)
    lenOfX = img.shape[1]
    lenOfY = img.shape[0]
    neighbourhoodGray = []
    for i in xAsix:
        for j in yAsix:
            if i >= 0 and i < lenOfX and j >= 0 and j < lenOfY:
                neighbourhoodGray.append(img[j,i])
    return neighbourhoodGray

img = cv2.imread('G:\\MachineLearning\\OpenCV\\IMG_8257.JPG',1)
img2gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(img2gray.shape)
#cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('Source Image', 800, 450)
cv2.imshow('Source Image', img2gray)

[rows,cols] = img2gray.shape
dim = 3
#newBorderImg = cv2.copyMakeBorder(img2gray, 1,1,1,1,cv2.BORDER_CONSTANT,value=0) #添加边界
newImg = img2gray
print(newImg[0:3, 111:115])
#middle = int(dim ** 2 / 2)
#print(middle)
for y in range(rows - 1,-1, -1):
    for x in range(0, cols):
        #tempssss = np.array(getNeighbourhood(newBorderImg,x,y,dim))
        temp_array = np.sort(np.array(getNeighbourhood(newImg,x,y,dim)))
        
        middle = int((len(temp_array) - 1) / 2)
        if x == 113 and y == 1:
            print(temp_array)
            print(middle)
            print(temp_array[middle])
        #newImg[x][y] = temp_array[middle]
        newImg.itemset((y,x),temp_array[middle])

MedianBlurImg = cv2.medianBlur(img2gray, dim)        
        
#cv2.namedWindow('NewImage', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('NewImage', 800, 450)
cv2.imshow('NewImage', newImg)
print(newImg[0:3, 111:115])

#cv2.namedWindow('MedianBlurImg', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('MedianBlurImg', 800, 450)
cv2.imshow('MedianBlurImg', MedianBlurImg)
print(MedianBlurImg[0:3, 111:115])

diff = np.abs(newImg - MedianBlurImg - 0.0)
print(diff)
print(np.mean(diff > 0))
print(np.where(diff != 0))
cv2.namedWindow('diff', cv2.WINDOW_NORMAL)
cv2.resizeWindow('diff', 800, 450)
cv2.imshow('diff', diff)


cv2.waitKey(0)
cv2.destroyAllWindows()


(388, 690)
[[242 243 243 243]
 [242 243 243 243]
 [242 242 242 242]]
[242 242 242 242 243 243 243 243 243]
4
243
[[242 242 243 243]
 [242 242 243 243]
 [242 242 242 242]]
[[242 242 243 243]
 [242 242 242 243]
 [242 242 242 242]]
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
0.0452861198267
(array([  1,   1,   1, ..., 387, 387, 387], dtype=int64), array([113, 118, 153, ..., 486, 487, 492], dtype=int64))


In [1]:
#sobel算子
import cv2
import numpy as np


def getNeighbourhoodToMat(img, x, y, dim = 3):
    if dim % 2 == 0:
        return
    xAsix = range(x - int(dim / 2), x + int(dim / 2) + 1)
    yAsix = range(y - int(dim / 2), y + int(dim / 2) + 1)
    #print(xAsix)
    #print(yAsix)
    lenOfX = img.shape[1]
    lenOfY = img.shape[0]
    neighbourhoodGray = np.zeros((dim,dim))
    for i in range(dim):
        for j in range(dim):
            neighbourhoodGray[j,i] += img[yAsix[j]][xAsix[i]]
    return neighbourhoodGray

img = cv2.imread('G:\\MachineLearning\\OpenCV\\1920x1080.JPG',1)
img2grayOld = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img2gray = cv2.blur(img2grayOld, (5, 5))   #均值滤波
img2gray[img2gray < np.max(np.max(img2gray)) * 0.33] = 0   #阈值

cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
cv2.resizeWindow('Source Image', 800, 450)
cv2.imshow('Source Image', img2gray)

#print(img2gray[15:18,15:18])

[rows,cols] = img2gray.shape
sobelOperatorX = np.array([[-1,-2,-1],[0,0,0],[1,2,1]])
sobelOperatorY = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])

newBorderImg = cv2.copyMakeBorder(img2gray, 1,1,1,1,cv2.BORDER_CONSTANT,value=0) #添加边界
newImgX = img2gray
newImgY = img2gray
newImgXY = img2gray
for x in range(1,cols-1):
    for y in range(1,rows-1):
        tempArray = getNeighbourhoodToMat(img2gray,x,y)
        newValueX = np.abs(np.sum(tempArray * sobelOperatorX))
        newValueY = np.abs(np.sum(tempArray * sobelOperatorY))
        """        if x== 16 and y == 16:
                    print(tempArray)
                    print(newValueX)
                    print(newValueY)"""
        newValueXY = newValueX + newValueY
        newImgX.itemset((y - 1,x - 1),newValueX)
        newImgY.itemset((y - 1,x - 1),newValueY)
        newImgXY.itemset((y - 1,x - 1),newValueXY)

cv2.namedWindow('NewImageX', cv2.WINDOW_NORMAL)
cv2.resizeWindow('NewImageX', 800, 450)
cv2.imshow('NewImageX', newImgX)

cv2.namedWindow('NewImageY', cv2.WINDOW_NORMAL)
cv2.resizeWindow('NewImageY', 800, 450)
cv2.imshow('NewImageY', newImgY)

cv2.namedWindow('NewImageXY', cv2.WINDOW_NORMAL)
cv2.resizeWindow('NewImageXY', 800, 450)
cv2.imshow('NewImageXY', newImgXY)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#Canny算法
import cv2
import numpy as np


def getNeighbourhoodToMat(img, x, y, dim = 3):
    if dim % 2 == 0:
        return
    xAsix = range(x - int(dim / 2), x + int(dim / 2) + 1)
    yAsix = range(y - int(dim / 2), y + int(dim / 2) + 1)
    neighbourhoodGray = np.zeros((dim,dim))
    for i in range(dim):
        for j in range(dim):
            neighbourhoodGray[j,i] += img[yAsix[j],xAsix[i]]
    return neighbourhoodGray

#开始
#==============================================================================================================


lowThreshold = 50
highThreshold = 110


img = cv2.imread('G:\\MachineLearning\\OpenCV\\testPhoto.jpg',1)
img2grayOld = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('Source Image', 800, 450)
cv2.imshow('Source Image', img2grayOld)


#第一步，高斯滤波器
#==============================================================================================================

#mean_G, stddev_G = cv2.meanStdDev(img2grayOld)
#GaussianKsize = int(6 * stddev_G + 1)
#if GaussianKsize % 2 is 0:
#      GaussianKsize = GaussianKsize + 1
GaussianKsize = 9
#   采用长宽相同的核
gauBlurImg = cv2.GaussianBlur(img2grayOld, (GaussianKsize, GaussianKsize), 0, None, 0)
#cv2.namedWindow('GaussianBlur Image', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('GaussianBlur Image', 800, 450)
cv2.imshow('GaussianBlur Image', gauBlurImg)

#第二步，计算梯度方向和大小
#==============================================================================================================

#print(img2gray[15:18,15:18])

sobelOperatorX = np.array([[-1,-2,-1],[0,0,0],[1,2,1]])
sobelOperatorY = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
newBorderImg = cv2.copyMakeBorder(gauBlurImg, 1,1,1,1,cv2.BORDER_CONSTANT,value=0) #添加边界
#newImgX = np.zeros_like(newBorderImg)
#newImgY = np.zeros_like(newBorderImg)
imgSize = newBorderImg.shape
sobelXYImg = np.zeros(imgSize)
temp_sobelXYImg = np.zeros(imgSize)
sobelArctanY_XImg = np.zeros(imgSize)
newSobelImg = np.zeros(imgSize)

[rows,cols] = newBorderImg.shape



for x in range(1, cols - 1):
    for y in range(1, rows - 1):
        tempArray = getNeighbourhoodToMat(newBorderImg,x,y)
        newValueX = np.sum(tempArray * sobelOperatorX)
        newValueY = np.sum(tempArray * sobelOperatorY)
        newValueXY = np.sqrt(newValueX**2 + newValueY**2)
        if newValueX == 0:
            newValueArctanY_X = 0  #newValueX == 0时对应着垂直，无论是-90度还是+90度，都可以视为0度
        else:
            #因为法向与边缘成90度角，因此加上90度使[-pi/2,pi/2]转化为[0，pi]，也即转化为边缘的角度
            newValueArctanY_X = np.arctan(newValueY / newValueX) + np.pi / 2   
        
        temp_sobelXYImg[y, x] = newValueXY
        sobelArctanY_XImg[y, x] = newValueArctanY_X
#print(np.max(sobelArctanY_XImg) * 180 / np.pi)
#print(np.min(sobelArctanY_XImg) * 180 / np.pi)

#第三步 非最大抑制处理梯度幅值图像
#==============================================================================================================

angles = [0]
for i in range(1,8,2):
    angles.append(np.pi * i / 8 )
angles.append(np.pi)
#print(np.array(angles) * 180 / np.pi)
adj = [((0,-1),(0,1)),((-1,1),(1,-1)),((-1,0),(1,0)),((1,1),(-1,-1)),((0,-1),(0,1))]
for x in range(1,cols-1):
    for y in range(1,rows-1):
        for i in range(1, 6):
            if sobelArctanY_XImg[y, x] >= angles[i - 1] and sobelArctanY_XImg[y, x] < angles[i]:

                M_neib1 = temp_sobelXYImg[y + adj[i - 1][0][0],x + adj[i - 1][0][1]]
                M_neib2 = temp_sobelXYImg[y + adj[i - 1][1][0],x + adj[i - 1][1][1]]
                M_this = temp_sobelXYImg[y, x]
                if M_this >= M_neib1 and M_this >= M_neib2:
                    newSobelImg[y,x] = M_this
                else:
                    newSobelImg[y,x] = 0
                break

#newSobelImg = (newSobelImg - np.min(newSobelImg)) / np.max(newSobelImg) * 255
#cv2.namedWindow('newSobelImg', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('newSobelImg', 800, 450)
#cv2.imshow('newSobelImg', newSobelImg)


#第四部，高低阈值
#==============================================================================================================
highThImg = np.ones_like(newSobelImg) *255
highThImg[newSobelImg < highThreshold] = 0

lowThImg = np.ones_like(newSobelImg) * 255
lowThImg[newSobelImg < lowThreshold] = 0

cv2.imshow('lowThImg', lowThImg)
cv2.imshow('highThImg', highThImg)
lowThImg = lowThImg - highThImg

outImg = np.zeros(lowThImg.shape)
connectedStack = []

neightPoints = [(-1,0),(1,0),(1,1),(-1,-1),(0,1),(0,-1),(-1,1),(1,-1)]

for x in range(1,cols-1):
    for y in range(1,rows-1):
        if highThImg[y, x] != 0:
            connectedStack.append((y, x))
            while len(connectedStack) != 0:
                curPoint = connectedStack.pop()
                for i in range(0, len(neightPoints)):
                    adjx = curPoint[1] + neightPoints[i][1]
                    adjy = curPoint[0] + neightPoints[i][0]
                    if lowThImg[adjy, adjx] != 0:
                        connectedStack.append((adjy, adjx))
                        lowThImg[adjy, adjx] = 0
                        outImg[adjy, adjx] = 255
                        
outImg += highThImg
cv2.imshow('outImg', outImg[1:-2,1:-2])
    

cannyImgGray = cv2.Canny(gauBlurImg,50,130)
cv2.imshow('cannyImgGray', cannyImgGray)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
#试验模块
import cv2
import numpy as np
temp = [[2,3],[3,5]]
s = [[6,2,1,5,6],[534,2,1,98,12],[23,67,9,45,821],[1234425,1345,645,234,567],[93,123537,9869,354,3802]]
q =  [[5,2,1,5,6],[2,2,1,48,12],[23,67,9,45,1],[5,1345,45,4,567],[93,1537,9,354,2]]
#s[2][3]
s[temp[0][0]][temp[0][1]]
x = 3
t = range(x - int(3 / 2), x + int(3 / 2))
print(t[1])
mean, stddev = cv2.meanStdDev(np.array([2,3,4]))
old = np.array(s)
print(old)
new = cv2.copyMakeBorder(old , 1,1,1,1,cv2.BORDER_CONSTANT,value=0)
print(new)
diff = np.array(s) - np.array(q) - 0.0
print(diff)

dim = 3
neighbourhoodGray = np.zeros((dim,dim))
for i in range(dim):
    for j in range(dim):
        neighbourhoodGray[i,j] += 10
print(neighbourhoodGray)
print(np.arctan(1) - np.pi / 4)
np.pi / 8 * 180 / np.pi
print("======================")
x = np.array(s)
N = x.shape[0]
T = x - 1/N *(np.dot(np.ones([1,N]),x))
#print(T)
#print(x - np.mean(x,axis=0) - T)

var = np.dot(np.ones([N,N]), T * T)/N
var_auto = np.var(x,axis = 0)
print(var - var_auto)

print("=========")
print(np.ones_like(var))

3
[[      6       2       1       5       6]
 [    534       2       1      98      12]
 [     23      67       9      45     821]
 [1234425    1345     645     234     567]
 [     93  123537    9869     354    3802]]
[[      0       0       0       0       0       0       0]
 [      0       6       2       1       5       6       0]
 [      0     534       2       1      98      12       0]
 [      0      23      67       9      45     821       0]
 [      0 1234425    1345     645     234     567       0]
 [      0      93  123537    9869     354    3802       0]
 [      0       0       0       0       0       0       0]]
[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00]
 [  5.32000000e+02   0.00000000e+00   0.00000000e+00   5.00000000e+01
    0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    8.20000000e+02]
 [  1.23442000e+06   0.00000000e+00   6.00000000e+02   2.30000000e+02
    0.00000000e+00]
 [  0.00