In [1]:
#拆分成8个bit图层，每个图层是8bit灰度值中的1bit
import cv2
import numpy as np

img = cv2.imread('../images/1920x1080.JPG',1)
img2gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

print(np.max(img2gray))
cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
cv2.resizeWindow('Source Image', 640, 480)
cv2.imshow('Source Image', img2gray)

allOnes = np.ones_like(img2gray)

bitMash = 1

for i in range(8):
    bitMash = 1 << i
    mashMat = bitMash * allOnes
    #print(mashMat)
    #print(img2gray)
    #print()
    newImg = cv2.bitwise_and(mashMat,img2gray)
    imgName = 'Bit ' + str(i) + " Image"
    cv2.namedWindow(imgName, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(imgName, 640, 480)
    cv2.imshow(imgName, newImg)

cv2.waitKey(0)
cv2.destroyAllWindows()


255


In [ ]:
#局部增强
import cv2
import numpy as np


def getNeighbourhood(img, x, y, dim = 3):
    if dim % 2 == 0:
        return
    xAsix = range(x - int(dim / 2), x + int(dim / 2) + 1)
    yAsix = range(y - int(dim / 2), y + int(dim / 2) + 1)
    #print(xAsix)
    #print(yAsix)
    lenOfX = img.shape[1]
    lenOfY = img.shape[0]
    neighbourhoodGray = []
    for i in xAsix:
        for j in yAsix:
            if i >= 0 and i < lenOfX and j >= 0 and j < lenOfY:
                neighbourhoodGray.append(img[j,i])
    return neighbourhoodGray

img = cv2.imread('../images/1920x1080.JPG',1)
img2gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
cv2.resizeWindow('Source Image', 800, 450)
cv2.imshow('Source Image', img2gray)

[rows,cols] = img2gray.shape
mean_G, stddev_G = cv2.meanStdDev(img2gray)
newImg = img2gray
for x in range(cols):
    for y in range(rows):
        mean, stddev = cv2.meanStdDev(np.array(getNeighbourhood(img2gray,x,y)))
        if mean <= 0.8 * mean_G and stddev >= 0.02 * stddev_G and  stddev <= 0.4 * stddev_G:
            newImg[y,x] = np.min([255, 4 * img2gray[y,x]])

cv2.namedWindow('NewImage', cv2.WINDOW_NORMAL)
cv2.resizeWindow('NewImage', 800, 450)
cv2.imshow('NewImage', newImg)

cv2.waitKey(0)
cv2.destroyAllWindows()




In [12]:
#中值滤波器实现
import cv2
import numpy as np

#注意归一化！！！！！
def getNeighbourhood(img, x, y, dim = 3):
    if dim % 2 == 0:
        return
    xAsix = range(x - int(dim / 2), x + int(dim / 2) + 1)
    yAsix = range(y - int(dim / 2), y + int(dim / 2) + 1)
    #print(xAsix)
    #print(yAsix)
    lenOfX = img.shape[1]
    lenOfY = img.shape[0]
    neighbourhoodGray = []
    for i in xAsix:
        for j in yAsix:
            if i >= 0 and i < lenOfX and j >= 0 and j < lenOfY:
                neighbourhoodGray.append(img[j,i])
    return neighbourhoodGray

img = cv2.imread('../images/IMG_8257.JPG',1)
img2gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
print(img2gray.shape)
#cv2.namedWindow('Source Image', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('Source Image', 800, 450)
cv2.imshow('Source Image', img2gray)

[rows,cols] = img2gray.shape
dim = 3
#newBorderImg = cv2.copyMakeBorder(img2gray, 1,1,1,1,cv2.BORDER_CONSTANT,value=0) #添加边界
newImg = img2gray
print(newImg[0:3, 111:115])
#middle = int(dim ** 2 / 2)
#print(middle)
for y in range(rows - 1,-1, -1):
    for x in range(0, cols):
        #tempssss = np.array(getNeighbourhood(newBorderImg,x,y,dim))
        temp_array = np.sort(np.array(getNeighbourhood(newImg,x,y,dim)))
        
        middle = int((len(temp_array) - 1) / 2)
        if x == 113 and y == 1:
            print(temp_array)
            print(middle)
            print(temp_array[middle])
        #newImg[x][y] = temp_array[middle]
        newImg.itemset((y,x),temp_array[middle])

MedianBlurImg = cv2.medianBlur(img2gray, dim)        
        
#cv2.namedWindow('NewImage', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('NewImage', 800, 450)
cv2.imshow('NewImage', newImg)
print(newImg[0:3, 111:115])

#cv2.namedWindow('MedianBlurImg', cv2.WINDOW_NORMAL)
#cv2.resizeWindow('MedianBlurImg', 800, 450)
cv2.imshow('MedianBlurImg', MedianBlurImg)
print(MedianBlurImg[0:3, 111:115])

diff = np.abs(newImg - MedianBlurImg - 0.0)
print(diff)
print(np.mean(diff > 0))
print(np.where(diff != 0))
cv2.namedWindow('diff', cv2.WINDOW_NORMAL)
cv2.resizeWindow('diff', 800, 450)
cv2.imshow('diff', diff)


cv2.waitKey(0)
cv2.destroyAllWindows()


(388, 690)
[[242 243 243 243]
 [242 243 243 243]
 [242 242 242 242]]
[242 242 242 242 243 243 243 243 243]
4
243
[[242 242 243 243]
 [242 242 243 243]
 [242 242 242 242]]
[[242 242 243 243]
 [242 242 242 243]
 [242 242 242 242]]
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
0.0452861198267
(array([  1,   1,   1, ..., 387, 387, 387], dtype=int64), array([113, 118, 153, ..., 486, 487, 492], dtype=int64))
